# Generated by Django 3.1 on 2020-12-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscription_valid_through',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
