# Generated by Django 3.1 on 2020-12-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_subscription_valid_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'stripe_customer_id',
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ('valid_through', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser', name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customuser', name='subscription_valid_through',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='accounts.subscription',
            ),
        ),
    ]
