stages:
  - test
  - build
  - deploy
  - management

# jobs for build, deploy and management are in these included files
include:
  - local: /gitlab-ci/do-base.yml
  - local: "/gitlab-ci/dev.yml"

image: docker:19.03.1
services:
  - docker:19.03.5-dind

Pytest:
  image: python:3.8
  stage: test
  services:
    - postgres:13.1
    - redis:6.0.9-alpine
  variables:
    DJANGO_SETTINGS_MODULE: "backend.settings.gitlab_ci"
    SECRET_KEY: "secret"
    DEBUG: "True"
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - cd backend
    - pip install -r requirements/base.txt
    - pip install -r requirements/test.txt
    - flake8
    - black -l 79 -S --diff .
    - pytest --cov --cov-config=.coveragerc
  coverage: '/TOTAL.+ ([0-9]{1,3}\.[0-9]{1,3}%)/'
