FROM python:3.8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ARG LINKEDIN_OAUTH2_KEY
ARG LINKEDIN_OAUTH2_SECRET
ENV LINKEDIN_OAUTH2_KEY=$LINKEDIN_OAUTH2_KEY
ENV LINKEDIN_OAUTH2_SECRET=$LINKEDIN_OAUTH2_SECRET
RUN mkdir /code
RUN useradd -m app
USER app
WORKDIR /code
COPY --chown=app:app requirements/base.txt /code/requirements/
ENV PATH="/home/app/.local/bin:${PATH}"
RUN pip install --user -r requirements/base.txt
COPY --chown=app:app . /code/
