FROM python:3.8
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir /code
RUN useradd -m app
USER app
WORKDIR /code
COPY --chown=app:app requirements/base.txt /code/requirements/
ENV PATH="/home/app/.local/bin:${PATH}"
RUN pip install --user -r requirements/base.txt
COPY --chown=app:app . /code/
